
steps:

# copy service account key
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://chimenesjr-certs/book-255910-cb84b5f5eb61.json', './file-ingest-back/secrets/']

# build Dockerfile-gcp
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', './file-ingest-back/Dockerfile-gcp', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID', '.']

# push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID']
  id: 'Docker push'

# deploy on cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '$REPO_NAME', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
  env:
  - 'ASPNETCORE_ENVIRONMENT=Production'
  - 'GOOGLE_APPLICATION_CREDENTIALS=./secrets/book-255910-cb84b5f5eb61.json'
  id: 'Deploy to Cloud Run'



# Push to Container Registry
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID']
